"""add more fields to PlantMeasurement

Revision ID: 39752972f98a
Revises: add_indexes_to_plant_tables
Create Date: 2025-10-20 15:44:16.094943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39752972f98a'
down_revision: Union[str, Sequence[str], None] = 'add_indexes_to_plant_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_files_plant_id'), table_name='plant_files')
    op.drop_index(op.f('idx_files_status'), table_name='plant_files')
    op.drop_index(op.f('idx_fruits_measurement_id'), table_name='plant_fruits')
    op.add_column('plant_measurements', sa.Column('cum_yield_per_plant', sa.Float(), nullable=True))
    op.add_column('plant_measurements', sa.Column('class_1', sa.Float(), nullable=True))
    op.add_column('plant_measurements', sa.Column('length_of_cropping', sa.Float(), nullable=True))
    op.add_column('plant_measurements', sa.Column('growth_habit', sa.String(), nullable=True))
    op.add_column('plant_measurements', sa.Column('field', sa.String(), nullable=True))
    op.drop_index(op.f('idx_measurements_date'), table_name='plant_measurements')
    op.drop_index(op.f('idx_measurements_plant_id'), table_name='plant_measurements')
    op.drop_index(op.f('idx_plants_breeder_id'), table_name='plants')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_plants_breeder_id'), 'plants', ['breeder_id'], unique=False)
    op.create_index(op.f('idx_measurements_plant_id'), 'plant_measurements', ['plant_id'], unique=False)
    op.create_index(op.f('idx_measurements_date'), 'plant_measurements', ['date'], unique=False)
    op.drop_column('plant_measurements', 'field')
    op.drop_column('plant_measurements', 'growth_habit')
    op.drop_column('plant_measurements', 'length_of_cropping')
    op.drop_column('plant_measurements', 'class_1')
    op.drop_column('plant_measurements', 'cum_yield_per_plant')
    op.create_index(op.f('idx_fruits_measurement_id'), 'plant_fruits', ['measurement_id'], unique=False)
    op.create_index(op.f('idx_files_status'), 'plant_files', ['status'], unique=False)
    op.create_index(op.f('idx_files_plant_id'), 'plant_files', ['plant_id'], unique=False)
    # ### end Alembic commands ###
