"""update PlantFile remove  unique constraint

Revision ID: 58923d25f066
Revises: 9c3393b41bfd
Create Date: 2025-09-07 10:47:40.353965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58923d25f066'
down_revision: Union[str, Sequence[str], None] = '9c3393b41bfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uix_plant_file_date'), 'plant_files', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uix_plant_file_date'), 'plant_files', ['plant_id', 'date'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
