"""update PlantMeasure

Revision ID: 63fb7db8979d
Revises: c0a69d062ce9
Create Date: 2025-09-06 10:28:12.413559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63fb7db8979d'
down_revision: Union[str, Sequence[str], None] = 'c0a69d062ce9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant_fruits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('measurement_id', sa.Integer(), nullable=False),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('mass', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['measurement_id'], ['plant_measurements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('plant_measurements', 'fruit_height')
    op.drop_column('plant_measurements', 'fruit_width')
    op.drop_column('plant_measurements', 'mass')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant_measurements', sa.Column('mass', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('plant_measurements', sa.Column('fruit_width', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('plant_measurements', sa.Column('fruit_height', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_table('plant_fruits')
    # ### end Alembic commands ###
