"""update PlantFile add unique constraints

Revision ID: 9c3393b41bfd
Revises: 63fb7db8979d
Create Date: 2025-09-07 10:40:27.605757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c3393b41bfd'
down_revision: Union[str, Sequence[str], None] = '63fb7db8979d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_plant_file_date', 'plant_files', ['plant_id', 'date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_plant_file_date', 'plant_files', type_='unique')
    # ### end Alembic commands ###
