"""add more traits to measurement table

Revision ID: bb992bdb76f2
Revises: dd7a895d6d21
Create Date: 2025-10-22 14:33:11.773761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb992bdb76f2'
down_revision: Union[str, Sequence[str], None] = 'dd7a895d6d21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant_measurements', sa.Column('petiole_length', sa.Float(), nullable=True))
    op.add_column('plant_measurements', sa.Column('petiole_strength', sa.Float(), nullable=True))
    op.add_column('plant_measurements', sa.Column('petiole_radius', sa.Float(), nullable=True))
    op.add_column('plant_measurements', sa.Column('truss_length', sa.Float(), nullable=True))
    op.add_column('plant_measurements', sa.Column('truss_strength', sa.Float(), nullable=True))
    op.add_column('plant_measurements', sa.Column('truss_radius', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plant_measurements', 'truss_radius')
    op.drop_column('plant_measurements', 'truss_strength')
    op.drop_column('plant_measurements', 'truss_length')
    op.drop_column('plant_measurements', 'petiole_radius')
    op.drop_column('plant_measurements', 'petiole_strength')
    op.drop_column('plant_measurements', 'petiole_length')
    # ### end Alembic commands ###
