"""initialize database

Revision ID: c0a69d062ce9
Revises: 
Create Date: 2025-09-06 00:54:12.970853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0a69d062ce9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breeders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_breeders_name'), 'breeders', ['name'], unique=True)
    op.create_table('plants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('breeder_id', sa.Integer(), nullable=False),
    sa.Column('plant_code', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['breeder_id'], ['breeders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('breeder_id', 'plant_code', name='uix_breeder_plant')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='role'), nullable=False),
    sa.Column('breeder_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['breeder_id'], ['breeders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('plant_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_type', sa.Enum('TWO_D', 'THREE_D', name='filetypeenum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='filestatusenum'), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plant_measurements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('variety', sa.String(), nullable=True),
    sa.Column('biomass', sa.Float(), nullable=True),
    sa.Column('canopy_density', sa.Float(), nullable=True),
    sa.Column('ripe', sa.Integer(), nullable=True),
    sa.Column('part_ripe', sa.Integer(), nullable=True),
    sa.Column('unripe', sa.Integer(), nullable=True),
    sa.Column('flower', sa.Integer(), nullable=True),
    sa.Column('fruit_width', sa.Float(), nullable=True),
    sa.Column('fruit_height', sa.Float(), nullable=True),
    sa.Column('mass', sa.Float(), nullable=True),
    sa.Column('yield_per_plant', sa.Float(), nullable=True),
    sa.Column('crop_composition', sa.Float(), nullable=True),
    sa.Column('plant_height', sa.Float(), nullable=True),
    sa.Column('exg', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plant_id', 'date', name='uix_plant_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plant_measurements')
    op.drop_table('plant_files')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('plants')
    op.drop_index(op.f('ix_breeders_name'), table_name='breeders')
    op.drop_table('breeders')
    # ### end Alembic commands ###
