"""update fields to PlantMeasurement

Revision ID: dd7a895d6d21
Revises: 39752972f98a
Create Date: 2025-10-20 15:50:43.983687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd7a895d6d21'
down_revision: Union[str, Sequence[str], None] = '39752972f98a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plant_measurements', 'growth_habit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant_measurements', sa.Column('growth_habit', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
