"""add growth_habit and fruit_shape to measurements

Revision ID: ec7ac33aea4e
Revises: bb992bdb76f2
Create Date: 2025-10-23 09:44:07.702231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec7ac33aea4e'
down_revision: Union[str, Sequence[str], None] = 'bb992bdb76f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant_measurements', sa.Column('growth_habit', sa.String(), nullable=True))
    op.add_column('plant_measurements', sa.Column('fruit_shape', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plant_measurements', 'fruit_shape')
    op.drop_column('plant_measurements', 'growth_habit')
    # ### end Alembic commands ###
